# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
# $schema: "https://golangci-lint.run/jsonschema/golangci.jsonschema.json"

linters:
  disable:
    - "gofumpt"
  presets:
    - "format"
