services:

  mariadb:
    # image: mariadb:11.3.2
    build:
      context: container-images/corpora/db
      dockerfile: ./Dockerfile # relative to 'context' field
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./tmp:/tmp/dumps

  adminer:
    image: adminer:5.4.2@sha256:9ead7e126d795c549ce8ad1c7bb8f30a231e061bad769eda704c39c7f609888d
    restart: always
    ports:
      - 8066:8080

#SELECT w_id, word, freq
#select count(*)
#FROM words
#WHERE CHAR_LENGTH(word) = 5 AND word RLIKE "^[a-zA-Z]+$" AND freq > 1
#ORDER BY freq DESC
##LIMIT 500
