app = 'lettr'
primary_region = 'ams'

[build]
  dockerfile = "container-images/app/Dockerfile"
  build-target = "prod"

[env]
  PORT = '9026'

[http_service]
  internal_port = 9026
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
